# Generated by Django 5.2.16 on 2026-07-15 03:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('contacto_nombre', models.CharField(blank=True, max_length=255)),
                ('contacto_email', models.EmailField(blank=True, max_length=254)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('renta_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('copias_incluidas_bn', models.PositiveIntegerField(default=0)),
                ('copias_incluidas_color', models.PositiveIntegerField(default=0)),
                ('costo_excedente_bn', models.DecimalField(decimal_places=4, max_digits=10)),
                ('costo_excedente_color', models.DecimalField(decimal_places=4, max_digits=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
                ('dia_corte_facturacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('carpeta_drive_destino_id', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('terminado', 'Terminado')], default='activo', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.cliente')),
            ],
            options={
                'ordering': ['numero_contrato'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('metodo_lectura', models.CharField(choices=[('api_3manager', 'API 3-Manager'), ('api_printaudit', 'API PrintAudit'), ('manual', 'Manual')], max_length=20)),
                ('id_externo_3manager', models.CharField(blank=True, max_length=100, null=True)),
                ('id_externo_printaudit', models.CharField(blank=True, max_length=100, null=True)),
                ('permite_reset_contador', models.BooleanField(default=False)),
                ('tope_contador', models.PositiveIntegerField(blank=True, null=True)),
                ('estado_actual', models.CharField(choices=[('activo', 'Activo'), ('en_taller', 'En taller'), ('sin_asignar', 'Sin asignar'), ('baja', 'Baja')], default='sin_asignar', max_length=20)),
            ],
            options={
                'ordering': ['numero_serie'],
                'indexes': [models.Index(fields=['metodo_lectura', 'estado_actual'], name='core_equipo_metodo__fe8885_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('lectura_inicial_referencia_bn', models.PositiveIntegerField()),
                ('lectura_inicial_referencia_color', models.PositiveIntegerField()),
                ('lectura_cierre_bn', models.PositiveIntegerField(blank=True, null=True)),
                ('lectura_cierre_color', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_red_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='core.contrato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='core.equipo')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('periodo_anio', models.PositiveIntegerField()),
                ('consumo_excedente_bn', models.PositiveIntegerField(default=0)),
                ('consumo_excedente_color', models.PositiveIntegerField(default=0)),
                ('monto_renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_excedente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_url', models.URLField(blank=True)),
                ('excel_url', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('ok', 'Ok'), ('pendiente', 'Pendiente'), ('error_archivo', 'Error de archivo')], default='pendiente', max_length=20)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='core.contrato')),
            ],
            options={
                'ordering': ['-periodo_anio', '-periodo_mes'],
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('lectura_bn', models.PositiveIntegerField()),
                ('lectura_color', models.PositiveIntegerField()),
                ('origen', models.CharField(choices=[('api_3manager', 'API 3-Manager'), ('api_printaudit', 'API PrintAudit'), ('manual', 'Manual')], max_length=20)),
                ('estado_auditoria', models.CharField(choices=[('ok', 'Ok'), ('alerta', 'Alerta'), ('error', 'Error')], default='ok', max_length=10)),
                ('detalle_auditoria', models.JSONField(blank=True, default=dict)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='core.asignacion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('ok', 'Ok'), ('pendiente', 'Pendiente (auditoría)'), ('error_archivo', 'Error de archivo'), ('error', 'Error')], max_length=20)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('enlaces_generados', models.JSONField(blank=True, default=dict)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.contrato')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado', 'dia_corte_facturacion'], name='core_contra_estado_ece9b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('dia_corte_facturacion__gte', 1), ('dia_corte_facturacion__lte', 31)), name='contrato_dia_corte_valido'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['contrato', 'fecha_fin'], name='core_asigna_contrat_0ff277_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('equipo',), name='unique_asignacion_activa_por_equipo'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('contrato', 'periodo_mes', 'periodo_anio'), name='unique_factura_por_periodo'),
        ),
        migrations.AddIndex(
            model_name='lectura',
            index=models.Index(fields=['fecha', 'estado_auditoria'], name='core_lectur_fecha_26638e_idx'),
        ),
        migrations.AddConstraint(
            model_name='lectura',
            constraint=models.UniqueConstraint(fields=('asignacion', 'fecha'), name='unique_lectura_por_dia'),
        ),
        migrations.AddIndex(
            model_name='logejecucion',
            index=models.Index(fields=['timestamp', 'estado'], name='core_logeje_timesta_b637ab_idx'),
        ),
    ]
