# Generated by Django 5.2.16 on 2026-07-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='asignacion',
            name='unique_asignacion_activa_por_equipo',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('equipo',), name='unique_asignacion_activa_por_equipo', violation_error_message='Este equipo ya tiene una asignación activa (sin fecha de fin). Cierra esa asignación antes de crear una nueva.'),
        ),
        migrations.AlterConstraint(
            model_name='contrato',
            name='contrato_dia_corte_valido',
            constraint=models.CheckConstraint(condition=models.Q(('dia_corte_facturacion__gte', 1), ('dia_corte_facturacion__lte', 31)), name='contrato_dia_corte_valido', violation_error_message='El día de corte debe estar entre 1 y 31.'),
        ),
        migrations.AlterConstraint(
            model_name='factura',
            name='unique_factura_por_periodo',
            constraint=models.UniqueConstraint(fields=('contrato', 'periodo_mes', 'periodo_anio'), name='unique_factura_por_periodo', violation_error_message='Ya existe una factura para este contrato en ese periodo.'),
        ),
        migrations.AlterConstraint(
            model_name='lectura',
            name='unique_lectura_por_dia',
            constraint=models.UniqueConstraint(fields=('asignacion', 'fecha'), name='unique_lectura_por_dia', violation_error_message='Ya existe una lectura registrada para esta asignación en esa fecha.'),
        ),
    ]
