# Generated by Django 5.2.16 on 2026-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_asignacion_unique_asignacion_activa_por_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_cuenta_3manager',
            field=models.CharField(blank=True, help_text='accountId (GUID) de este cliente en 3-Manager, visible en la URL al ver la cuenta en la plataforma. Requerido solo si algún equipo de este cliente usa metodo_lectura=api_3manager.', max_length=100, verbose_name='ID de cuenta en 3-Manager'),
        ),
    ]
