# Generated by Django 5.2.16 on 2026-07-15 19:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_id_cuenta_3manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='carpeta_drive_destino_id',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='excel_url',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='factura',
            name='excel_archivo',
            field=models.FileField(blank=True, upload_to=core.models._ruta_documento_factura),
        ),
        migrations.AddField(
            model_name='factura',
            name='pdf_archivo',
            field=models.FileField(blank=True, upload_to=core.models._ruta_documento_factura),
        ),
    ]
