# Generated by Django 5.2.16 on 2026-07-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contrato_carpeta_drive_destino_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fin real del rango de lecturas facturado.', null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Inicio real del rango de lecturas facturado. Ancla el siguiente periodo (ver core.procesamiento_facturacion).', null=True),
        ),
    ]
