# Generated by Django 5.2.16 on 2026-07-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_factura_fecha_fin_factura_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Peso mexicano (MXN)'), ('USD', 'Dólar estadounidense (USD)')], default='MXN', max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Peso mexicano (MXN)'), ('USD', 'Dólar estadounidense (USD)')], default='MXN', help_text='Copiada del contrato al momento de calcular la factura, para que quede fija aunque el contrato cambie de moneda después.', max_length=3),
        ),
    ]
