# Generated by Django 5.2.16 on 2026-07-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contrato_moneda_factura_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='emisores/')),
            ],
            options={
                'verbose_name': 'Empresa emisora',
                'verbose_name_plural': 'Empresas emisoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='emisor',
            field=models.ForeignKey(help_text='Razón social que factura este contrato (define el logo/nombre del PDF y Excel). Nulo solo en contratos creados antes de esta función; el Admin lo exige de aquí en adelante.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.empresaemisora'),
        ),
        migrations.AddField(
            model_name='factura',
            name='emisor',
            field=models.ForeignKey(blank=True, help_text='Copiado del contrato al momento de facturar, para que quede fijo aunque el contrato cambie de emisor después.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='core.empresaemisora'),
        ),
    ]
