# Generated by Django 5.2.16 on 2026-07-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_empresas_emisoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='en_linea_api',
            field=models.BooleanField(blank=True, help_text='Estatus de conectividad reportado por la fuente de lectura (p. ej. isOffline de 3-Manager). Nulo para equipos de lectura manual o que aún no se han sincronizado.', null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ultima_actualizacion_api',
            field=models.DateTimeField(blank=True, help_text='Última vez que el equipo reportó datos a su fuente de lectura (ver sincronizar_lecturas).', null=True),
        ),
    ]
