# Generated by Django 5.2.16 on 2026-08-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_equipo_en_linea_api_equipo_ultima_actualizacion_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Área o departamento donde está instalado el equipo dentro de las instalaciones del cliente (ej. Almacén, Recepción, Contabilidad). Aparece en el PDF y Excel de factura para clientes que segmentan el cobro por área.', max_length=100, verbose_name='Departamento / Ubicación'),
        ),
    ]
