"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-f$5rp4513c#oe+_q#5hie!jg9u8v*2npf97j-x%e-9%p4oc*@$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'documentos' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


EMPRESA_NOMBRE = os.environ.get('EMPRESA_NOMBRE', 'Mi Empresa de Renta de Equipos')


# Correo / notificaciones

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'facturacion@example.com')
NOTIFICACIONES_EMAIL_DESTINO = [
    correo.strip() for correo in os.environ.get('NOTIFICACIONES_EMAIL_DESTINO', '').split(',') if correo.strip()
]


# Integraciones externas (lectura de contadores)

# 3-Manager: API pública v1.2, autenticación OAuth2 "password grant".
# API_3MANAGER_TENANT es el subdominio de tu URL de login en 3manager
# (p. ej. si entras por https://app.3manager.com, el tenant es "app").
# Nota: se usa `or` (no el segundo argumento de os.environ.get) porque una
# variable presente en .env pero vacía ("X=") sigue devolviendo "" con
# .get(clave, default) — el default de os.environ.get solo aplica si la
# variable no existe en absoluto.
API_3MANAGER_BASE_URL = os.environ.get('API_3MANAGER_BASE_URL') or 'http://printinginsightsapi.3manager.com'
API_3MANAGER_DEVICES_PATH = os.environ.get('API_3MANAGER_DEVICES_PATH') or '/public/accounts/{account_id}/devices'
API_3MANAGER_TENANT = os.environ.get('API_3MANAGER_TENANT', '')
API_3MANAGER_USERNAME = os.environ.get('API_3MANAGER_USERNAME', '')
API_3MANAGER_PASSWORD = os.environ.get('API_3MANAGER_PASSWORD', '')

API_PRINTAUDIT_BASE_URL = os.environ.get('API_PRINTAUDIT_BASE_URL', '')
API_PRINTAUDIT_API_KEY = os.environ.get('API_PRINTAUDIT_API_KEY', '')

API_INTEGRATIONS_TIMEOUT = int(os.environ.get('API_INTEGRATIONS_TIMEOUT', '15'))

GOOGLE_SERVICE_ACCOUNT_JSON = os.environ.get('GOOGLE_SERVICE_ACCOUNT_JSON', '')
GOOGLE_SERVICE_ACCOUNT_FILE = os.environ.get('GOOGLE_SERVICE_ACCOUNT_FILE', '')


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Tema del Admin (django-jazzmin)
# https://django-jazzmin.readthedocs.io/

JAZZMIN_SETTINGS = {
    "site_title": f"{EMPRESA_NOMBRE} Admin",
    "site_header": EMPRESA_NOMBRE,
    "site_brand": EMPRESA_NOMBRE,
    "welcome_sign": f"Sistema de Facturación — {EMPRESA_NOMBRE}",
    "copyright": EMPRESA_NOMBRE,
    "search_model": ["core.Contrato", "core.Equipo", "core.Cliente"],

    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["core", "auth"],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.Cliente": "fas fa-building",
        "core.Contrato": "fas fa-file-signature",
        "core.Equipo": "fas fa-print",
        "core.Asignacion": "fas fa-link",
        "core.Lectura": "fas fa-tachometer-alt",
        "core.Factura": "fas fa-file-invoice-dollar",
        "core.LogEjecucion": "fas fa-history",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-indigo",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_child_indent": True,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
